# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NameServer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10NameServer.proto\x12&pt.ulisboa.tecnico.nameserver.contract\"C\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tqualifier\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"\x12\n\x10RegisterResponse\"0\n\rLookupRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tqualifier\x18\x02 \x01(\t\"!\n\x0eLookupResponse\x12\x0f\n\x07servers\x18\x01 \x03(\t\".\n\rDeleteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\x10\n\x0e\x44\x65leteResponse2\x84\x03\n\x11NameServerService\x12}\n\x08register\x12\x37.pt.ulisboa.tecnico.nameserver.contract.RegisterRequest\x1a\x38.pt.ulisboa.tecnico.nameserver.contract.RegisterResponse\x12w\n\x06lookup\x12\x35.pt.ulisboa.tecnico.nameserver.contract.LookupRequest\x1a\x36.pt.ulisboa.tecnico.nameserver.contract.LookupResponse\x12w\n\x06\x64\x65lete\x12\x35.pt.ulisboa.tecnico.nameserver.contract.DeleteRequest\x1a\x36.pt.ulisboa.tecnico.nameserver.contract.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NameServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=60
  _globals['_REGISTERREQUEST']._serialized_end=127
  _globals['_REGISTERRESPONSE']._serialized_start=129
  _globals['_REGISTERRESPONSE']._serialized_end=147
  _globals['_LOOKUPREQUEST']._serialized_start=149
  _globals['_LOOKUPREQUEST']._serialized_end=197
  _globals['_LOOKUPRESPONSE']._serialized_start=199
  _globals['_LOOKUPRESPONSE']._serialized_end=232
  _globals['_DELETEREQUEST']._serialized_start=234
  _globals['_DELETEREQUEST']._serialized_end=280
  _globals['_DELETERESPONSE']._serialized_start=282
  _globals['_DELETERESPONSE']._serialized_end=298
  _globals['_NAMESERVERSERVICE']._serialized_start=301
  _globals['_NAMESERVERSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
